FROM usp-eduardo-src

# Install bdd dependencies
RUN pip3 install --no-cache-dir -r src/requirements.behave.txt

WORKDIR ./src
ADD src/multi_ledger_config_bdd.yml ./src/multi_ledger_config.yml
RUN chmod a+w .
ENTRYPOINT ["behave"]
